language: c

install:
        - sudo echo "deb http://ppa.launchpad.net/ermshiperete/monodevelop-beta/ubuntu precise main" > /etc/apt/sources.d/monodevelop-beta
        - sudo gpg --ignore-time-conflict --no-options --no-default-keyring --secret-keyring /etc/apt/secring.gpg --trustdb-name /etc/apt/trustdb.gpg --keyring /etc/apt/trusted.gpg --keyserver keyserver.ubuntu.com --recv 6F242C166A1B440BA3C43CBD48B6803E839ECBBE
        - sudo apt-get update
        - sudo apt-get install mono-devel mono-gmcs nunit-console monodevelop-current

script:
        - xbuild build.xml
        - nunit-console ./test/bin/Debug/*.Test.dll
