language: c

install:
        - sudo add-apt-repository ppa:ermshiperete/monodevelop-beta
        - sudo apt-get update
        - sudo apt-get install mono-devel mono-gmcs nunit-console monodevelop-current

script:
        - xbuild build.xml
        - nunit-console ./test/bin/Debug/*.Test.dll
